<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elearning.Shared\Elearning.Shared.Commons\Elearning.Shared.Commons.csproj" />
    <ProjectReference Include="..\Elearning.Shared\Elearning.Shared.Contracts\Elearning.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
