// <auto-generated />
using System;
using Elearning.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elearning.Infrastructure.Migrations
{
    [DbContext(typeof(ElearningDbContext))]
    [Migration("20260408171237_UpdateBaiHoc")]
    partial class UpdateBaiHoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elearning.Domain.Entities.BaiHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChuongHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChuongHocId");

                    b.ToTable("BaiHoc", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BaiLam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Diem")
                        .HasColumnType("real");

                    b.Property<Guid>("KyThiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiDiemBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiDiemNop")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KyThiId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BaiLam", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BoCauHoiOnTap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiangVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("TenBo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("BoCauHoiOnTap", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.CauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiangVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoaiCauHoi")
                        .HasColumnType("int");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("CauHoi", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.CauHoiKyThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KyThiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("KyThiId");

                    b.ToTable("CauHoiKyThi", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChiTietBaiLam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaiLamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DapAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("GiaTriNhap")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiLamId");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("DapAnId");

                    b.ToTable("ChiTietBaiLam", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChiTietBoCauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoCauHoiOnTapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoCauHoiOnTapId");

                    b.HasIndex("CauHoiId");

                    b.ToTable("ChiTietBoCauHoi", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChuongHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("ChuongHoc", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.DangKyKhoaHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DangKyKhoaHoc", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.DapAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("DapAn", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.DapAnDienKetQua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTriDung")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<float>("SaiSoChoPhep")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("DapAnDienKetQua", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.KhoaHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiangVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.KyThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("TenKyThi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("KyThi", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.MenhDeDungSai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaDung")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("MenhDeDungSai", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.TienDoHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaiHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThoiDiemHoanThanh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("TienDoHoc", (string)null);
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BaiHoc", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.ChuongHoc", "ChuongHoc")
                        .WithMany("BaiHocs")
                        .HasForeignKey("ChuongHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongHoc");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BaiLam", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.KyThi", "KyThi")
                        .WithMany("BaiLams")
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("BaiLams")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyThi");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BoCauHoiOnTap", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany("BoCauHoiOnTaps")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.CauHoi", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany("CauHois")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.CauHoiKyThi", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.CauHoi", "CauHoi")
                        .WithMany("CauHoiKyThis")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.KyThi", "KyThi")
                        .WithMany("CauHoiKyThis")
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("KyThi");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChiTietBaiLam", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.BaiLam", "BaiLam")
                        .WithMany("ChiTietBaiLams")
                        .HasForeignKey("BaiLamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.CauHoi", "CauHoi")
                        .WithMany("ChiTietBaiLams")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.DapAn", "DapAn")
                        .WithMany()
                        .HasForeignKey("DapAnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaiLam");

                    b.Navigation("CauHoi");

                    b.Navigation("DapAn");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChiTietBoCauHoi", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.BoCauHoiOnTap", "BoCauHoiOnTap")
                        .WithMany("ChiTietBoCauHois")
                        .HasForeignKey("BoCauHoiOnTapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.CauHoi", "CauHoi")
                        .WithMany("ChiTietBoCauHois")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoCauHoiOnTap");

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChuongHoc", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("ChuongHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.DangKyKhoaHoc", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.DapAn", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.CauHoi", "CauHoi")
                        .WithMany("DapAns")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.DapAnDienKetQua", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.KhoaHoc", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany("KhoaHocGiangDays")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.KyThi", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("KyThis")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.MenhDeDungSai", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.TienDoHoc", b =>
                {
                    b.HasOne("Elearning.Domain.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elearning.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("TienDoHocs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BaiLam", b =>
                {
                    b.Navigation("ChiTietBaiLams");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.BoCauHoiOnTap", b =>
                {
                    b.Navigation("ChiTietBoCauHois");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.CauHoi", b =>
                {
                    b.Navigation("CauHoiKyThis");

                    b.Navigation("ChiTietBaiLams");

                    b.Navigation("ChiTietBoCauHois");

                    b.Navigation("DapAns");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.ChuongHoc", b =>
                {
                    b.Navigation("BaiHocs");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.KhoaHoc", b =>
                {
                    b.Navigation("ChuongHocs");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("KyThis");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.KyThi", b =>
                {
                    b.Navigation("BaiLams");

                    b.Navigation("CauHoiKyThis");
                });

            modelBuilder.Entity("Elearning.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("BaiLams");

                    b.Navigation("BoCauHoiOnTaps");

                    b.Navigation("CauHois");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("KhoaHocGiangDays");

                    b.Navigation("TienDoHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
